<template>
  <v-btn
    fab
    fixed
    bottom
    right
    color="secondary"
    href="https://github.com/qianxiaoxiong/theme-blog"
    target="_blank"
    rel="noopener"
  >
    <v-icon>mdi-download</v-icon>
  </v-btn>
</template>
